name: Build repomix MCP Docker Image V2
on:
  # Trigger on push to the docker directory (where Dockerfile is maintained)
  push:
    branches:
      - main
    paths:
      - "repomix-mcp/**"
  pull_request:
    branches:
      - main
    paths:
      - "repomix-mcp/**"
  # Trigger on manual dispatch
  workflow_dispatch:

  # Schedule to check upstream repository hourly
  schedule:
    - cron: "* * * * 1"

  # Trigger when upstream repository is updated (using repository_dispatch)
  repository_dispatch:
    types: [upstream-update]

env:
  UPSTREAM_REPO: intelops/genval
  PROJECT_NAME: genval-mcp
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/repomix-mcp
  CWD: ${{GITHUB_WORKSPACE}}

jobs:
  steps:
    - name: Prepare Tags
      run: |
        BRANCH=${GITHUB_REF##*/}
        TS=$(date +%s)
        REVISION=${GITHUB_SHA::8}
        BUILD_ID="${BRANCH}-${REVISION}-${TS}"
        LATEST_ID=canary
        if [[ $GITHUB_REF == refs/tags/* ]]; then
         BUILD_ID=${GITHUB_REF/refs\/tags\//}
         LATEST_ID=latest
        fi
        echo BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') >> $GITHUB_OUTPUT
        echo BUILD_ID=${BUILD_ID} >> $GITHUB_OUTPUT
        echo LATEST_ID=${LATEST_ID} >> $GITHUB_OUTPUT

    - name: checkout upstream Genval repo
      uses: actions/checkout@v5
      with:
        ref: pre-main

    - name: COPY Dockerfile to curent context
      run: cp ./track-upstream/genval-Dockerfile .

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v6
      with:
        context: ${{ env.CWD }}
        file: ./track-upstream/genval-Dockerfile
        push: true
        tags: |
          ${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
          ${{ env.IMAGE }}:${{ steps.prep.outputs.LATEST_ID }}
